feature - new function for automatic reading mdr
samply/sample-locator pull request #46
Opened 2021-05-21 14:04 UTC by thkoehler11

- tiered menu instead dropdown for "add field"
- new bbmri logo

2021-05-21 14:33 UTC, alexanderkiel requested changes

2021-05-21 14:33 UTC, alexanderkiel commented on .vscode/launch.json
> +{
Please do not add IDE specific files.

2021-05-21 14:33 UTC, alexanderkiel commented on src/config/env.js
> +        "valueSetUrl": "http://hl7.org/fhir/sid/icd-10-gm"
This change is already present in the master. Please merge the master in develop and rebase onto it.

2021-05-21 14:33 UTC, alexanderkiel commented on src/environments/environment.ts
> +  mdrConfigGBN: (window as any).env.mdrConfigGBN || {},
Why can't we just use one mdrConfig like before?

2021-05-21 14:33 UTC, alexanderkiel commented on src/config/env.js
> +  window["env"]["mdrConfigCCDG"] =
Could we just have one env.js for GBN and one for BBMRI-ERIC?

2021-05-21 14:33 UTC, alexanderkiel commented on src/config/env.js
> +    "terminologyServerUrl": "https://samplelocator.bbmri.de/icd10"
This change is already present in the master. Please merge the master in develop and rebase onto it.

2021-05-21 14:33 UTC, alexanderkiel commented on src/app/component/work-in-progress/work-in-progress.component.html
> +      +++ BBMRI Locator +++ search for biosamples and associated data across multiple biobanks +++
We can't simply change this. Has to be a config.

2021-05-21 14:33 UTC, alexanderkiel commented on src/app/component/header/header.component.html
> +          <img src="assets/img/BBMRI-ERIC-gateway-for-health.svg" alt="BBMRI-ERIC-LOGO" class="bbmri-logo"/>
We can't simply change this. Has to be a config.

2021-06-25 08:59 UTC, lablans submitted a review, later dismissed
Some optional comments included

2021-11-19 13:22 UTC, alexanderkiel approved these changes

2021-11-19 13:23 UTC, merged